package com.minhdua.apps.constant.enums;

import com.minhdua.apps.document.Language;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ELanguage {
	AA(Language.builder().fullName("Afar").shortName("aa").localName("Afar").build()),
	AB(Language.builder().fullName("Abkhazian").shortName("ab").localName("Аҧсуа").build()),
	AF(Language.builder().fullName("Afrikaans").shortName("af").localName("Afrikaans").build()),
	AK(Language.builder().fullName("Akan").shortName("ak").localName("Akana").build()),
	ALS(Language.builder().fullName("Alemannic").shortName("als").localName("Alemannisch").build()),
	AM(Language.builder().fullName("Amharic").shortName("am").localName("አማርኛ").build()),
	AN(Language.builder().fullName("Aragonese").shortName("an").localName("Aragonés").build()),
	ANG(Language.builder().fullName("Angal").shortName("ang").localName("Angal Heneng").build()),
	ANG1(Language.builder().fullName("Anglo-Saxon / Old English").shortName("ang1").localName("Englisc").build()),
	AR(Language.builder().fullName("Arabic").shortName("ar").localName("العربية").build()),
	ARC(Language.builder().fullName("Aramaic").shortName("arc").localName("ܣܘܪܬ").build()),
	AS(Language.builder().fullName("Assamese").shortName("as").localName("অসমীয়া").build()),
	AST(Language.builder().fullName("Asturian").shortName("ast").localName("Asturianu").build()),
	AV(Language.builder().fullName("Avar").shortName("av").localName("Авар").build()),
	AWA(Language.builder().fullName("Awadhi").shortName("awa").localName("Awadhi").build()),
	AY(Language.builder().fullName("Aymara").shortName("ay").localName("Aymar").build()),
	AZ(Language.builder().fullName("Azerbaijani").shortName("az").localName("Azərbaycanca / آذربايجان").build()),
	BA(Language.builder().fullName("Bashkir").shortName("ba").localName("Башҡорт").build()),
	BAR(Language.builder().fullName("Bavarian").shortName("bar").localName("Boarisch").build()),
	BAT_SMG(Language.builder().fullName("Samogitian").shortName("bat-smg").localName("Žemaitėška").build()),
	BCL(Language.builder().fullName("Bikol").shortName("bcl").localName("Bikol Central").build()),
	BE(Language.builder().fullName("Belarusian").shortName("be").localName("Беларуская").build()),
	BE_X_OLD(Language.builder().fullName("Belarusian (Taraškievica)").shortName("be-x-old")
			.localName("Беларуская (тарашкевіца)").build()),
	BG(Language.builder().fullName("Bulgarian").shortName("bg").localName("Български").build()),
	BH(Language.builder().fullName("Bihari").shortName("bh").localName("भोजपुरी").build()),
	BI(Language.builder().fullName("Bislama").shortName("bi").localName("Bislama").build()),
	BM(Language.builder().fullName("Bambara").shortName("bm").localName("Bamanankan").build()),
	BN(Language.builder().fullName("Bengali").shortName("bn").localName("বাংলা").build()),
	BO(Language.builder().fullName("Tibetan").shortName("bo").localName("བོད་ཡིག / Bod skad").build()),
	BPY(Language.builder().fullName("Bishnupriya Manipuri").shortName("bpy").localName("ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী")
			.build()),
	BR(Language.builder().fullName("Breton").shortName("br").localName("Brezhoneg").build()),
	BS(Language.builder().fullName("Bosnian").shortName("bs").localName("Bosanski").build()),
	BUG(Language.builder().fullName("Buginese").shortName("bug").localName("ᨅᨔ ᨕᨘᨁᨗ / Basa Ugi").build()),
	BXR(Language.builder().fullName("Buriat (Russia)").shortName("bxr").localName("Буряад хэлэн").build()),
	CA(Language.builder().fullName("Catalan").shortName("ca").localName("Català").build()),
	CDO(Language.builder().fullName("Min Dong Chinese").shortName("cdo").localName("Mìng-dĕ̤ng-ngṳ̄ / 閩東語").build()),
	CE(Language.builder().fullName("Chechen").shortName("ce").localName("Нохчийн").build()),
	CEB(Language.builder().fullName("Cebuano").shortName("ceb").localName("Sinugboanong Binisaya").build()),
	CH(Language.builder().fullName("Chamorro").shortName("ch").localName("Chamoru").build()),
	CHO(Language.builder().fullName("Choctaw").shortName("cho").localName("Choctaw").build()),
	CHR(Language.builder().fullName("Cherokee").shortName("chr").localName("ᏣᎳᎩ").build()),
	CHY(Language.builder().fullName("Cheyenne").shortName("chy").localName("Tsetsêhestâhese").build()),
	CKB(Language.builder().fullName("Kurdish (Sorani)").shortName("ckb").localName("کوردی").build()),
	CO(Language.builder().fullName("Corsican").shortName("co").localName("Corsu").build()),
	CR(Language.builder().fullName("Cree").shortName("cr").localName("Nehiyaw").build()),
	CS(Language.builder().fullName("Czech").shortName("cs").localName("Česky").build()),
	CSB(Language.builder().fullName("Kashubian").shortName("csb").localName("Kaszëbsczi").build()),
	CU(Language.builder().fullName("Old Church Slavonic / Old Bulgarian").shortName("cu")
			.localName("словѣньскъ / slověnĭskŭ").build()),
	CV(Language.builder().fullName("Chuvash").shortName("cv").localName("Чăваш").build()),
	CY(Language.builder().fullName("Welsh").shortName("cy").localName("Cymraeg").build()),
	DA(Language.builder().fullName("Danish").shortName("da").localName("Dansk").build()),
	DE(Language.builder().fullName("German").shortName("de").localName("Deutsch").build()),
	DIQ(Language.builder().fullName("Dimli").shortName("diq").localName("Zazaki").build()),
	DSB(Language.builder().fullName("Lower Sorbian").shortName("dsb").localName("Dolnoserbski").build()),
	DV(Language.builder().fullName("Divehi").shortName("dv").localName("ދިވެހިބަސް").build()),
	DZ(Language.builder().fullName("Dzongkha").shortName("dz").localName("ཇོང་ཁ").build()),
	EE(Language.builder().fullName("Ewe").shortName("ee").localName("Ɛʋɛ").build()),
	EL(Language.builder().fullName("Greek").shortName("el").localName("Ελληνικά").build()),
	EN(Language.builder().fullName("English").shortName("en").localName("English").build()),
	EO(Language.builder().fullName("Esperanto").shortName("eo").localName("Esperanto").build()),
	ES(Language.builder().fullName("Spanish").shortName("es").localName("Español").build()),
	ET(Language.builder().fullName("Estonian").shortName("et").localName("Eesti").build()),
	EU(Language.builder().fullName("Basque").shortName("eu").localName("Euskara").build()),
	EXT(Language.builder().fullName("Extremaduran").shortName("ext").localName("Estremeñu").build()),
	FA(Language.builder().fullName("Persian").shortName("fa").localName("فارسی").build()),
	FF(Language.builder().fullName("Peul").shortName("ff").localName("Fulfulde").build()),
	FI(Language.builder().fullName("Finnish").shortName("fi").localName("Suomi").build()),
	FIU_VRO(Language.builder().fullName("Võro").shortName("fiu-vro").localName("Võro").build()),
	FJ(Language.builder().fullName("Fijian").shortName("fj").localName("Na Vosa Vakaviti").build()),
	FO(Language.builder().fullName("Faroese").shortName("fo").localName("Føroyskt").build()),
	FR(Language.builder().fullName("French").shortName("fr").localName("Français").build()),
	FRP(Language.builder().fullName("Arpitan / Franco-Provençal").shortName("frp")
			.localName("Arpitan / francoprovençal").build()),
	FUR(Language.builder().fullName("Friulian").shortName("fur").localName("Furlan").build()),
	FY(Language.builder().fullName("West Frisian").shortName("fy").localName("Frysk").build()),
	GA(Language.builder().fullName("Irish").shortName("ga").localName("Gaeilge").build()),
	GAN(Language.builder().fullName("Gan Chinese").shortName("gan").localName("贛語").build()),
	GBM(Language.builder().fullName("Garhwali").shortName("gbm").localName("गढ़वळी").build()),
	GD(Language.builder().fullName("Scottish Gaelic").shortName("gd").localName("Gàidhlig").build()),
	GIL(Language.builder().fullName("Gilbertese").shortName("gil").localName("Taetae ni kiribati").build()),
	GL(Language.builder().fullName("Galician").shortName("gl").localName("Galego").build()),
	GN(Language.builder().fullName("Guarani").shortName("gn").localName("Avañe'ẽ").build()),
	GOT(Language.builder().fullName("Gothic").shortName("got").localName("gutisk").build()),
	GU(Language.builder().fullName("Gujarati").shortName("gu").localName("ગુજરાતી").build()),
	GV(Language.builder().fullName("Manx").shortName("gv").localName("Gaelg").build()),
	HA(Language.builder().fullName("Hausa").shortName("ha").localName("هَوُسَ").build()),
	HAK(Language.builder().fullName("Hakka Chinese").shortName("hak").localName("客家語/Hak-kâ-ngî").build()),
	HAW(Language.builder().fullName("Hawaiian").shortName("haw").localName("Hawai`i").build()),
	HE(Language.builder().fullName("Hebrew").shortName("he").localName("עברית").build()),
	HI(Language.builder().fullName("Hindi").shortName("hi").localName("हिन्दी").build()),
	HO(Language.builder().fullName("Hiri Motu").shortName("ho").localName("Hiri Motu").build()),
	HR(Language.builder().fullName("Croatian").shortName("hr").localName("Hrvatski").build()),
	HT(Language.builder().fullName("Haitian").shortName("ht").localName("Krèyol ayisyen").build()),
	HU(Language.builder().fullName("Hungarian").shortName("hu").localName("Magyar").build()),
	HY(Language.builder().fullName("Armenian").shortName("hy").localName("Հայերեն").build()),
	HZ(Language.builder().fullName("Herero").shortName("hz").localName("Otsiherero").build()),
	IA(Language.builder().fullName("Interlingua").shortName("ia").localName("Interlingua").build()),
	ID(Language.builder().fullName("Indonesian").shortName("id").localName("Bahasa Indonesia").build()),
	IE(Language.builder().fullName("Interlingue").shortName("ie").localName("Interlingue").build()),
	IG(Language.builder().fullName("Igbo").shortName("ig").localName("Igbo").build()),
	II(Language.builder().fullName("Sichuan Yi").shortName("ii").localName("ꆇꉙ / 四川彝语").build()),
	IK(Language.builder().fullName("Inupiak").shortName("ik").localName("Iñupiak").build()),
	ILO(Language.builder().fullName("Ilokano").shortName("ilo").localName("Ilokano").build()),
	INH(Language.builder().fullName("Ingush").shortName("inh").localName("ГӀалгӀай").build()),
	IO(Language.builder().fullName("Ido").shortName("io").localName("Ido").build()),
	IS(Language.builder().fullName("Icelandic").shortName("is").localName("Íslenska").build()),
	IT(Language.builder().fullName("Italian").shortName("it").localName("Italiano").build()),
	IU(Language.builder().fullName("Inuktitut").shortName("iu").localName("ᐃᓄᒃᑎᑐᑦ").build()),
	JA(Language.builder().fullName("Japanese").shortName("ja").localName("日本語").build()),
	JBO(Language.builder().fullName("Lojban").shortName("jbo").localName("Lojban").build()),
	JV(Language.builder().fullName("Javanese").shortName("jv").localName("Basa Jawa").build()),
	KA(Language.builder().fullName("Georgian").shortName("ka").localName("ქართული").build()),
	KG(Language.builder().fullName("Kongo").shortName("kg").localName("KiKongo").build()),
	KI(Language.builder().fullName("Kikuyu").shortName("ki").localName("Gĩkũyũ").build()),
	KJ(Language.builder().fullName("Kuanyama").shortName("kj").localName("Kuanyama").build()),
	KK(Language.builder().fullName("Kazakh").shortName("kk").localName("Қазақша").build()),
	KL(Language.builder().fullName("Greenlandic").shortName("kl").localName("Kalaallisut").build()),
	KM(Language.builder().fullName("Cambodian").shortName("km").localName("ភាសាខ្មែរ").build()),
	KN(Language.builder().fullName("Kannada").shortName("kn").localName("ಕನ್ನಡ").build()),
	KHW(Language.builder().fullName("Khowar").shortName("khw").localName("کھوار").build()),
	KO(Language.builder().fullName("Korean").shortName("ko").localName("한국어").build()),
	KR(Language.builder().fullName("Kanuri").shortName("kr").localName("Kanuri").build()),
	KS(Language.builder().fullName("Kashmiri").shortName("ks").localName("कॉशुर / کٲشُر").build()),
	KSH(Language.builder().fullName("Ripuarian").shortName("ksh").localName("Ripoarisch").build()),
	KU(Language.builder().fullName("Kurdish (Kurmanji)").shortName("ku").localName("Kurdî").build()),
	KV(Language.builder().fullName("Komi").shortName("kv").localName("Коми").build()),
	KW(Language.builder().fullName("Cornish").shortName("kw").localName("Kernewek").build()),
	KY(Language.builder().fullName("Kirghiz").shortName("ky").localName("Kırgızca / Кыргызча").build()),
	LA(Language.builder().fullName("Latin").shortName("la").localName("Latina").build()),
	LAD(Language.builder().fullName("Ladino / Judeo-Spanish").shortName("lad").localName("Dzhudezmo / Djudeo-Espanyol")
			.build()),
	LAN(Language.builder().fullName("Lango").shortName("lan").localName("Leb Lango / Luo").build()),
	LB(Language.builder().fullName("Luxembourgish").shortName("lb").localName("Lëtzebuergesch").build()),
	LG(Language.builder().fullName("Ganda").shortName("lg").localName("Luganda").build()),
	LI(Language.builder().fullName("Limburgian").shortName("li").localName("Limburgs").build()),
	LIJ(Language.builder().fullName("Ligurian").shortName("lij").localName("Líguru").build()),
	LMO(Language.builder().fullName("Lombard").shortName("lmo").localName("Lumbaart").build()),
	LN(Language.builder().fullName("Lingala").shortName("ln").localName("Lingála").build()),
	LO(Language.builder().fullName("Laotian").shortName("lo").localName("ລາວ / Pha xa lao").build()),
	LZZ(Language.builder().fullName("Laz").shortName("lzz").localName("Lazuri / ლაზური").build()),
	LT(Language.builder().fullName("Lithuanian").shortName("lt").localName("Lietuvių").build()),
	LV(Language.builder().fullName("Latvian").shortName("lv").localName("Latviešu").build()),
	MAP_BMS(Language.builder().fullName("Banyumasan").shortName("map-bms").localName("Basa Banyumasan").build()),
	MG(Language.builder().fullName("Malagasy").shortName("mg").localName("Malagasy").build()),
	MAN(Language.builder().fullName("Mandarin").shortName("man").localName("官話/官话").build()),
	MH(Language.builder().fullName("Marshallese").shortName("mh").localName("Kajin Majel / Ebon").build()),
	MI(Language.builder().fullName("Māori").shortName("mi").localName("Māori").build()),
	MIN(Language.builder().fullName("Minangkabau").shortName("min").localName("Minangkabau").build()),
	MK(Language.builder().fullName("Macedonian").shortName("mk").localName("Македонски").build()),
	ML(Language.builder().fullName("Malayalam").shortName("ml").localName("മലയാളം").build()),
	MN(Language.builder().fullName("Mongolian").shortName("mn").localName("Монгол").build()),
	MO(Language.builder().fullName("Moldovan").shortName("mo").localName("Moldovenească").build()),
	MR(Language.builder().fullName("Marathi").shortName("mr").localName("मराठी").build()),
	MRH(Language.builder().fullName("Mara").shortName("mrh").localName("Mara").build()),
	MS(Language.builder().fullName("Malay").shortName("ms").localName("Bahasa Melayu").build()),
	MT(Language.builder().fullName("Maltese").shortName("mt").localName("bil-Malti").build()),
	MUS(Language.builder().fullName("Creek / Muskogee").shortName("mus").localName("Mvskoke").build()),
	MWL(Language.builder().fullName("Mirandese").shortName("mwl").localName("Mirandés").build()),
	MY(Language.builder().fullName("Burmese").shortName("my").localName("Myanmasa").build()),
	NA(Language.builder().fullName("Nauruan").shortName("na").localName("Dorerin Naoero").build()),
	NAH(Language.builder().fullName("Nahuatl").shortName("nah").localName("Nahuatl").build()),
	NAP(Language.builder().fullName("Neapolitan").shortName("nap").localName("Nnapulitano").build()),
	ND(Language.builder().fullName("North Ndebele").shortName("nd").localName("Sindebele").build()),
	NDS(Language.builder().fullName("Low German / Low Saxon").shortName("nds").localName("Plattdüütsch").build()),
	NDS_NL(Language.builder().fullName("Dutch Low Saxon").shortName("nds-nl").localName("Nedersaksisch").build()),
	NE(Language.builder().fullName("Nepali").shortName("ne").localName("नेपाली").build()),
	NEW(Language.builder().fullName("Newar").shortName("new").localName("नेपालभाषा / Newah Bhaye").build()),
	NG(Language.builder().fullName("Ndonga").shortName("ng").localName("Oshiwambo").build()),
	NL(Language.builder().fullName("Dutch").shortName("nl").localName("Nederlands").build()),
	NN(Language.builder().fullName("Norwegian Nynorsk").shortName("nn").localName("Norsk (nynorsk)").build()),
	NO(Language.builder().fullName("Norwegian").shortName("no").localName("Norsk (bokmål / riksmål)").build()),
	NR(Language.builder().fullName("South Ndebele").shortName("nr").localName("isiNdebele").build()),
	NSO(Language.builder().fullName("Northern Sotho").shortName("nso").localName("Sesotho sa Leboa / Sepedi").build()),
	NRM(Language.builder().fullName("Norman").shortName("nrm").localName("Nouormand / Normaund").build()),
	NV(Language.builder().fullName("Navajo").shortName("nv").localName("Diné bizaad").build()),
	NY(Language.builder().fullName("Chichewa").shortName("ny").localName("Chi-Chewa").build()),
	OC(Language.builder().fullName("Occitan").shortName("oc").localName("Occitan").build()),
	OJ(Language.builder().fullName("Ojibwa").shortName("oj").localName("ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin").build()),
	OM(Language.builder().fullName("Oromo").shortName("om").localName("Oromoo").build()),
	OR(Language.builder().fullName("Oriya").shortName("or").localName("ଓଡ଼ିଆ").build()),
	OS(Language.builder().fullName("Ossetian / Ossetic").shortName("os").localName("Иронау").build()),
	PA(Language.builder().fullName("Panjabi / Punjabi").shortName("pa").localName("ਪੰਜਾਬੀ / پنجابی").build()),
	PAG(Language.builder().fullName("Pangasinan").shortName("pag").localName("Pangasinan").build()),
	PAM(Language.builder().fullName("Kapampangan").shortName("pam").localName("Kapampangan").build()),
	PAP(Language.builder().fullName("Papiamentu").shortName("pap").localName("Papiamentu").build()),
	PDC(Language.builder().fullName("Pennsylvania German").shortName("pdc").localName("Deitsch").build()),
	PI(Language.builder().fullName("Pali").shortName("pi").localName("Pāli / पाऴि").build()),
	PIH(Language.builder().fullName("Norfolk").shortName("pih").localName("Norfuk").build()),
	PL(Language.builder().fullName("Polish").shortName("pl").localName("Polski").build()),
	PMS(Language.builder().fullName("Piedmontese").shortName("pms").localName("Piemontèis").build()),
	PS(Language.builder().fullName("Pashto").shortName("ps").localName("پښتو").build()),
	PT(Language.builder().fullName("Portuguese").shortName("pt").localName("Português").build()),
	QU(Language.builder().fullName("Quechua").shortName("qu").localName("Runa Simi").build()),
	RM(Language.builder().fullName("Raeto Romance").shortName("rm").localName("Rumantsch").build()),
	RMY(Language.builder().fullName("Romani").shortName("rmy").localName("Romani / रोमानी").build()),
	RN(Language.builder().fullName("Kirundi").shortName("rn").localName("Kirundi").build()),
	RO(Language.builder().fullName("Romanian").shortName("ro").localName("Română").build()),
	ROA_RUP(Language.builder().fullName("Aromanian").shortName("roa-rup").localName("Armâneashti").build()),
	RU(Language.builder().fullName("Russian").shortName("ru").localName("Русский").build()),
	RW(Language.builder().fullName("Rwandi").shortName("rw").localName("Kinyarwandi").build()),
	SA(Language.builder().fullName("Sanskrit").shortName("sa").localName("संस्कृतम्").build()),
	SC(Language.builder().fullName("Sardinian").shortName("sc").localName("Sardu").build()),
	SCN(Language.builder().fullName("Sicilian").shortName("scn").localName("Sicilianu").build()),
	SCO(Language.builder().fullName("Scots").shortName("sco").localName("Scots").build()),
	SD(Language.builder().fullName("Sindhi").shortName("sd").localName("सिंधी / سنڌي‎").build()),
	SE(Language.builder().fullName("Northern Sami").shortName("se").localName("Davvisámegiella").build()),
	SG(Language.builder().fullName("Sango").shortName("sg").localName("Sängö").build()),
	SH(Language.builder().fullName("Serbo-Croatian").shortName("sh").localName("Srpskohrvatski / Српскохрватски")
			.build()),
	SI(Language.builder().fullName("Sinhalese").shortName("si").localName("සිංහල").build()),
	SIMPLE(Language.builder().fullName("Simple English").shortName("simple").localName("Simple English").build()),
	SK(Language.builder().fullName("Slovak").shortName("sk").localName("Slovenčina").build()),
	SL(Language.builder().fullName("Slovenian").shortName("sl").localName("Slovenščina").build()),
	SM(Language.builder().fullName("Samoan").shortName("sm").localName("Gagana Samoa").build()),
	SN(Language.builder().fullName("Shona").shortName("sn").localName("chiShona").build()),
	SO(Language.builder().fullName("Somalia").shortName("so").localName("Soomaaliga").build()),
	SQ(Language.builder().fullName("Albanian").shortName("sq").localName("Shqip").build()),
	SR(Language.builder().fullName("Serbian").shortName("sr").localName("Српски").build()),
	SS(Language.builder().fullName("Swati").shortName("ss").localName("SiSwati").build()),
	ST(Language.builder().fullName("Southern Sotho").shortName("st").localName("Sesotho").build()),
	SU(Language.builder().fullName("Sundanese").shortName("su").localName("Basa Sunda").build()),
	SV(Language.builder().fullName("Swedish").shortName("sv").localName("Svenska").build()),
	SW(Language.builder().fullName("Swahili").shortName("sw").localName("Kiswahili").build()),
	TA(Language.builder().fullName("Tamil").shortName("ta").localName("தமிழ்").build()),
	TE(Language.builder().fullName("Telugu").shortName("te").localName("తెలుగు").build()),
	TET(Language.builder().fullName("Tetum").shortName("tet").localName("Tetun").build()),
	TG(Language.builder().fullName("Tajik").shortName("tg").localName("Тоҷикӣ").build()),
	TH(Language.builder().fullName("Thai").shortName("th").localName("ไทย / Phasa Thai").build()),
	TI(Language.builder().fullName("Tigrinya").shortName("ti").localName("ትግርኛ").build()),
	TK(Language.builder().fullName("Turkmen").shortName("tk").localName("Туркмен / تركمن").build()),
	TL(Language.builder().fullName("Tagalog").shortName("tl").localName("Tagalog").build()),
	TLH(Language.builder().fullName("Klingon").shortName("tlh").localName("tlhIngan-Hol").build()),
	TN(Language.builder().fullName("Tswana").shortName("tn").localName("Setswana").build()),
	TO(Language.builder().fullName("Tonga").shortName("to").localName("Lea Faka-Tonga").build()),
	TPI(Language.builder().fullName("Tok Pisin").shortName("tpi").localName("Tok Pisin").build()),
	TR(Language.builder().fullName("Turkish").shortName("tr").localName("Türkçe").build()),
	TS(Language.builder().fullName("Tsonga").shortName("ts").localName("Xitsonga").build()),
	TT(Language.builder().fullName("Tatar").shortName("tt").localName("Tatarça").build()),
	TUM(Language.builder().fullName("Tumbuka").shortName("tum").localName("chiTumbuka").build()),
	TW(Language.builder().fullName("Twi").shortName("tw").localName("Twi").build()),
	TY(Language.builder().fullName("Tahitian").shortName("ty").localName("Reo Mā`ohi").build()),
	UDM(Language.builder().fullName("Udmurt").shortName("udm").localName("Удмурт кыл").build()),
	UG(Language.builder().fullName("Uyghur").shortName("ug").localName("Uyƣurqə / ئۇيغۇرچە").build()),
	UK(Language.builder().fullName("Ukrainian").shortName("uk").localName("Українська").build()),
	UR(Language.builder().fullName("Urdu").shortName("ur").localName("اردو").build()),
	UZ(Language.builder().fullName("Uzbek").shortName("uz").localName("Ўзбек").build()),
	UZ_AF(Language.builder().fullName("Uzbeki Afghanistan").shortName("uz_AF").localName("اوزبیکی").build()),
	VE(Language.builder().fullName("Venda").shortName("ve").localName("Tshivenḓa").build()),
	VI(Language.builder().fullName("Vietnamese").shortName("vi").localName("Việtnam").build()),
	VEC(Language.builder().fullName("Venetian").shortName("vec").localName("Vèneto").build()),
	VLS(Language.builder().fullName("West Flemish").shortName("vls").localName("West-Vlaoms").build()),
	VO(Language.builder().fullName("Volapük").shortName("vo").localName("Volapük").build()),
	WA(Language.builder().fullName("Walloon").shortName("wa").localName("Walon").build()),
	WAR(Language.builder().fullName("Waray / Samar-Leyte Visayan").shortName("war")
			.localName("Winaray / Binisaya Lineyte-Samarnon").build()),
	WO(Language.builder().fullName("Wolof").shortName("wo").localName("Wollof").build()),
	XAL(Language.builder().fullName("Kalmyk").shortName("xal").localName("Хальмг").build()),
	XH(Language.builder().fullName("Xhosa").shortName("xh").localName("isiXhosa").build()),
	XMF(Language.builder().fullName("Megrelian").shortName("xmf").localName("მარგალური").build()),
	YI(Language.builder().fullName("Yiddish").shortName("yi").localName("ייִדיש").build()),
	YO(Language.builder().fullName("Yoruba").shortName("yo").localName("Yorùbá").build()),
	ZA(Language.builder().fullName("Zhuang").shortName("za").localName("Cuengh / Tôô / 壮语").build()),
	ZH(Language.builder().fullName("Chinese").shortName("zh").localName("中文").build()),
	ZH_CLASSICAL(Language.builder().fullName("Classical Chinese").shortName("zh-classical").localName("文言").build()),
	ZH_MIN_NAN(Language.builder().fullName("Minnan").shortName("zh-min-nan").localName("Bân-lâm-gú").build()),
	ZH_YUE(Language.builder().fullName("Cantonese").shortName("zh-yue").localName("粵語 / 粤语").build()),
	ZU(Language.builder().fullName("Zulu").shortName("zu").localName("isiZulu").build());

	private Language language;
}